const LIKED_VIDEOS = "LIKED_VIDEOS";
const WATCH_LATER = "WATCH_LATER";
const DEFAULT_PLAYLISTS = [LIKED_VIDEOS, WATCH_LATER];

module.exports = {
  LIKED_VIDEOS,
  WATCH_LATER,
  DEFAULT_PLAYLISTS,
};
